### ISSUE TITLE
Issue using IOS

### ISSUE THREAD

**Issue by hershkoy** [Sopur/Discord-user-bots#7]
I have a project that works for me on windows 10 and linux (ubuntu)
When I tried to run on MacOs, I got this error:

```
Reading configuration
(node:693) UnhandledPromiseRejectionWarning: FetchError: Invalid response body while trying to fetch https://discord.com/api/v9/users/@me: invalid distance too far back
    at Gunzip.<anonymous> (/snapshot/discord-marketing/node_modules/discord-user-bots/node_modules/node-fetch/lib/index.js:400:12)
    at Gunzip.emit (events.js:412:35)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(Use Discord_Bot-macos --trace-warnings ... to show where the warning was created)
(node:693) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag --unhandled-rejections=strict (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:693) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Is there a way to fix this issue?

**Comment by Sopur** [comment]
Does this happen before the bot receives a ready event?

**Comment by hershkoy** [comment]
Yes, it is before

**Comment by Sopur** [comment]
Make a new folder, do
`
npm init -y && npm i node-fetch@2
`
In the terminal inside the project folder
make a file called index.js with the contents of:
`
const fetch = require("node-fetch");
fetch("https://discord.com/api/v9/users/@me").then(console.log);
`
And do 
`
node .
`
Tell me what is outputted in the console.

**Comment by Sopur** [comment]
My bad, insert 
```js
const fetch = require("node-fetch");
fetch("https://discord.com/api/v9/users/@me", {
headers: {
                accept: "*/*",
                "accept-language": "en-US",
                authorization: <Insert token>,
                "sec-ch-ua": '" Not;A Brand";v="99", "Google Chrome";v="91", "Chromium";v="91"',
                "sec-ch-ua-mobile": "?0",
                "sec-fetch-dest": "empty",
                "sec-fetch-mode": "cors",
                "sec-fetch-site": "same-origin",
            },
            referrer: "https://discord.com/login?redirect_to=%2Fchannels%2F%40me",
            referrerPolicy: "strict-origin-when-cross-origin",
            body: null,
            method: "GET",
            mode: "cors",
        }).then(console.log);
```
instead.

**Comment by hershkoy** [comment]
The macos computer is not mine, it was a friend. I will try to reach out and do it with him, though it can take some time.
